services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      API_PORT: 4000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
      - 443:3000
    environment:
      NEXT_PUBLIC_HOST: 'ws://backend'
